### ISSUE TITLE
Panel crashes when the Space Engineers server restarts

### ISSUE THREAD

**Issue by AWL-Gaming** [sam4413/AMPLink#1]
The current panel behavior is set to give a fatal crash and stop working whenever it loses connection to the game server (Manual or automated game server restarts for example).
This is less than ideal for a panel that is supposed to get the server status all the time (unattended), so I would like to suggest this feature being implemented, or at least a way for the panel app to check and auto-reconnect itself on a set interval.

```
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (D:\AMPLink-main\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (D:\AMPLink-main\node_modules\mysql\lib\Connection.js:94:28)
    at Socket.<anonymous> (D:\AMPLink-main\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (D:\AMPLink-main\node_modules\mysql\lib\Connection.js:423:8)
    at Protocol.emit (node:events:513:28)
    at Protocol._delegateError (D:\AMPLink-main\node_modules\mysql\lib\protocol\Protocol.js:398:10)
    at Protocol.end (D:\AMPLink-main\node_modules\mysql\lib\protocol\Protocol.js:116:8)
    at Socket.<anonymous> (D:\AMPLink-main\node_modules\mysql\lib\Connection.js:94:28)
    [... lines matching original stack trace ...]
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  fatal: true,
  code: 'PROTOCOL_CONNECTION_LOST'
}
Node.js v19.3.0
AMPLink has crashed. Press any key to restart, or close the application.
Press any key to continue . . .
```

**Comment by AWL-Gaming** [comment]
A possible workaround is to remove the "pause" option from the .bat file, and replace it with `timeout /t 1 >nul`

**Comment by sam4413** [comment]
Thanks for reporting this issue, I'll get to it ASAP and publish a update in a few hours. 
AMPLink should be automatically reconnecting to the server, however it seems that it is not working correctly. I am pretty new to GitHub, my bad for the long response. I'll let you know when it's fixed.

**Comment by sam4413** [comment]
Update 0.0.3 alpha is out, fixed
